import Script from 'next/script'
import '../styles/globals.css'
import Head from 'next/head'
import Navbar from './Navbar'
import { AuthProvider } from '../contexts/AuthContext'





function MyApp({ Component, pageProps }) {
  return<>
   <div className=''>
  <Head>
     <title>Youtube Tool</title>
        <meta name="Agency Website" content="Generated by Youtube Tool" />
      {/* bootstrap css cdn*/}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
       
      </Head>
   

      {/* bootstrap js cdn*/}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
    <Navbar/> 
 

    <AuthProvider>
            <Component {...pageProps} />
        </AuthProvider>

 


</div>
 
  </>
}

export default MyApp
