name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        port: 22
        script: |
          # Start SSH agent and add the SSH key
          eval $(ssh-agent -s)
          echo "${{ secrets.DROPLET_SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null

          # Create and set permissions for SSH directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add GitHub to known hosts to prevent SSH warning
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Navigate to project directory
          cd /var/www/Youtube-Tool-Frontend

          # Set the correct Git remote URL for SSH
          git remote set-url origin git@github.com:MicrotersAsad/Youtube-Tool-Frontend.git

          # Pull the latest changes from GitHub
          git pull origin main

          # Install dependencies and build project
          npm install
          npm run build

          # Restart the application using PM2
          pm2 restart youtube-tool-frontend
